### ISSUE TITLE
Build POT3D with -gpu=unified memory

### ISSUE THREAD

**Issue by khayamgondal** [predsci/POT3D#12]
Based on[ this article](https://developer.nvidia.com/blog/simplifying-gpu-programming-for-hpc-with-the-nvidia-grace-hopper-superchip/#pot3d) we can build POT3D with unified memory and all OpenACC directives removed. Can anyone please provide instructions on how to remove all OpenACC directives?

**Comment by sumseq** [comment]
See the version contained in the "src/stdpar" folder.  
That version has zero directives.

**Comment by sumseq** [comment]
Sorry - it looks like the code in the stdpar directory had some openmp target due to a merge problem.
I have fixed it so now the src/stdpar code is directive-free and uses do concurrent for reductions as well.

**Comment by khayamgondal** [comment]
Thanks @sumseq. I started by just copying ./build_gpu_nvidia.sh to the base directory and running but the command fails with the following output.

mpich version: 4.0-3
CUDA: 12.4
GPU: H100
Its an ARM machine - Nvidia GH200

```
[root@r8-u37 ~/POT3D 2003]# ./build_gpu_nvidia.sh
=== STARTING POT3D BUILD ===
==> Entering src directory...
==> Removing old Makefile...
==> Generating Makefile from Makefile.template...
==> Compiling code...
!!> ERROR!  pot3d executable not found.  Build most likely failed.
            Contents of src/build.err:
gfortran: error: unrecognized debug output level ‘pu=ccnative,mem:separate’
gfortran: error: unrecognized command-line option ‘-stdpar=gpu’; did you mean ‘-std=gnu’?
gfortran: error: unrecognized command-line option ‘-acc=gpu’
gfortran: error: unrecognized command-line option ‘-mp=gpu’
gfortran: error: unrecognized command-line option ‘-Minfo=accel’
gfortran: error: unrecognized command-line option ‘-cudalib=cusparse’
make: *** [Makefile:39: psi_io.o] Error 1
```

**Comment by sumseq** [comment]
You are using gfortran, which does not support stdpar for nvidia GPU and has very different flags.
You will need to install and activate (load the module) NVHPC: https://developer.nvidia.com/hpc-sdk
You also may want to disable cusparse to start with (see the build script for details).

**Comment by sumseq** [comment]
Also, the build script is designed for the main version of the code (that includes some directives).
If you want to test the stdpar version, you should first build the main code, than copy the Makefile into the stdpar folder, modify the Makefile to use unified memory and remove acc and mp flags, and then and run "Make".  You can then copy the pot3d binary to the "bin" folder and then run the validation.sh script.

**Comment by khayamgondal** [comment]
Thanks for getting back quickly @sumseq . At this point I am just buildling the main code. 
I am using NVIDIA's HPC container and have built and installed HDF5.
However running, ./build_gpu_nvidia.sh fails with following error - Looks like its not able to find -lhdf5hl_fortran 


```
   6123, Generating NVIDIA GPU code
       6123,   ! blockidx%x threadidx%x auto-collapsed
             Loop parallelized across CUDA thread blocks, CUDA threads(128) collapse(3) ! blockidx%x threadidx%x
   6123, Generating implicit copyin(phi(1:nrm1+1,1:nt,1:np),dr(1:nrm1)) [if not already present]
         Generating implicit copyout(br(1:nrm1,1:nt,1:np)) [if not already present]
   6129, Generating NVIDIA GPU code
       6129,   ! blockidx%x threadidx%x auto-collapsed
             Loop parallelized across CUDA thread blocks, CUDA threads(128) collapse(3) ! blockidx%x threadidx%x
   6129, Generating implicit copyin(dt(1:ntm1)) [if not already present]
         Generating implicit copyout(bt(1:nr,1:ntm1,1:np)) [if not already present]
         Generating implicit copyin(rh(1:nr),phi(1:nr,1:ntm1+1,1:np)) [if not already present]
   6135, Generating NVIDIA GPU code
       6135,   ! blockidx%x threadidx%x auto-collapsed
             Loop parallelized across CUDA thread blocks, CUDA threads(128) collapse(3) ! blockidx%x threadidx%x
   6135, Generating implicit copyin(dp(1:npm1)) [if not already present]
         Generating implicit copyout(bp(1:nr,1:nt,1:npm1)) [if not already present]
         Generating implicit copyin(sth(1:nt),rh(1:nr),phi(1:nr,1:nt,1:npm1+1)) [if not already present]
magnetic_energy:
   6185, Generating implicit map(tofrom:dth(:),dph(:),drh(:),rh(:),bt(:,:,:),bp(:,:,:),br(:,:,:),sth(:))
/usr/bin/ld: cannot find -lhdf5hl_fortran: No such file or directory
pgacclnk: child process exit status 1: /usr/bin/ld
make: *** [Makefile:28: all] Error 2
```
I build HDF5 as following 

```
cmake -DCMAKE_C_COMPILER=`which mpicc` -DHDF5_BUILD_FORTRAN=ON  -DHDF5_ENABLE_PARALLEL=ON BUILD_TESTING=OFF DCMAKE_Fortran_MODULE_DIRECTORY=/opt/nvidia/hpc_sdk/Linux_aarch64/24.11/comm_libs/12.6/openmpi4/openmpi-4.1.5/lib/  ..

make -j8 install
```
HDF5 config 

```
 /usr/local/HDF_Group/HDF5/1.14.5/bin/h5cc -showconfig
        SUMMARY OF THE HDF5 CONFIGURATION
        =================================

General Information:
-------------------
                   HDF5 Version: 1.14.5
                  Configured on: 2024-12-23
                  Configured by: Unix Makefiles
                    Host system: Linux-6.8.0-1017-nvidia-64k
              Uname information: Linux
                       Byte sex: little-endian
             Installation point: /usr/local/HDF_Group/HDF5/1.14.5

Compiling Options:
------------------
                     Build Mode: Release
              Debugging Symbols: OFF
                        Asserts: OFF
                      Profiling: OFF
             Optimization Level: OFF

Linking Options:
----------------
                      Libraries:
  Statically Linked Executables: OFF
                        LDFLAGS:
                     H5_LDFLAGS:
                     AM_LDFLAGS:
                Extra libraries: m;dl
                       Archiver: /usr/bin/ar
                       AR_FLAGS:
                         Ranlib: /usr/bin/ranlib

Languages:
----------
                              C: YES
                     C Compiler: /opt/nvidia/hpc_sdk/Linux_aarch64/24.11/comm_libs/mpi/bin/mpicc 24.11.0
                       CPPFLAGS:
                    H5_CPPFLAGS:
                    AM_CPPFLAGS:
                         CFLAGS:  -c99  -Minform=warn -s
                      H5_CFLAGS:
                      AM_CFLAGS:
               Shared C Library: YES
               Static C Library: YES

                        Fortran: ON
               Fortran Compiler: /opt/nvidia/hpc_sdk/Linux_aarch64/24.11/compilers/bin/nvfortran 24.11.0
                  Fortran Flags:
               H5 Fortran Flags:
               AM Fortran Flags:
         Shared Fortran Library: YES
         Static Fortran Library: YES
               Module Directory: /pot3d/hdf5-hdf5_1.14.5/bld/mod

                            C++: OFF
                   C++ Compiler:
                      C++ Flags:
                   H5 C++ Flags:
                   AM C++ Flags:
             Shared C++ Library: YES
             Static C++ Library: YES

                           JAVA: OFF
                  JAVA Compiler:

Features:
---------
                     Parallel HDF5: ON
  Parallel Filtered Dataset Writes: ON
                Large Parallel I/O: ON
                High-level library: ON
Dimension scales w/ new references:
                  Build HDF5 Tests: OFF
                  Build HDF5 Tools: ON
                   Build GIF Tools: OFF
                      Threadsafety: OFF
               Default API mapping: v114
    With deprecated public symbols: ON
            I/O filters (external):  DEFLATE
                  _Float16 support: ON
                     Map (H5M) API: OFF
                        Direct VFD: OFF
                        Mirror VFD: OFF
                     Subfiling VFD: OFF
                (Read-Only) S3 VFD: OFF
              (Read-Only) HDFS VFD: OFF
    Packages w/ extra debug output:
                       API Tracing: OFF
              Using memory checker: OFF
                  Use file locking: best-effort
         Strict File Format Checks: OFF
      Optimization Instrumentation:
```

LD path

```
echo $LD_LIBRARY_PATH
/usr/local/HDF_Group/HDF5/1.14.5/lib/:/opt/nvidia/hpc_sdk/Linux_aarch64/24.11/comm_libs/nvshmem/lib:/opt/nvidia/hpc_sdk/Linux_aarch64/24.11/comm_libs/nccl/lib:/opt/nvidia/hpc_sdk/Linux_aarch64/24.11/math_libs/lib64:/opt/nvidia/hpc_sdk/Linux_aarch64/24.11/compilers/lib:/opt/nvidia/hpc_sdk/Linux_aarch64/24.11/compilers/extras/qd/lib:/opt/nvidia/hpc_sdk/Linux_aarch64/24.11/cuda/lib64::
```

**Comment by sumseq** [comment]
Hi,

Sometimes the name of the hdf5 libraries to link are different depending on
the hdf5 installation.

For example, on Ubuntu the libraries have a "_serial" in them, and
since you have installed the parallel version, the names might be different
as well.

I would double check that the names in the "-l" flags match the names of
the library files.

 - Ron

**Comment by khayamgondal** [comment]
Thanks Ron, Here are the flags in src/Makefile 

`LDFLAGS = -L/usr/local/hdf5/lib/ -lhdf5_fortran -lhdf5hl_fortran -lhdf5 -lhdf5_hl`

These are different than the files I have in my /usr/local/hdf5/lib/  folder and I am not sure which of these file names I need to use in LDFLAGS. Can you help me here?

```
 ls /usr/local/hdf5/lib/
libhdf5.a                libhdf5_f90cstub.so.310.3.1  libhdf5_hl.so.310.0.5           libhdf5_hl_fortran.so.310.0.5
libhdf5.settings         libhdf5_fortran.a            libhdf5_hl_f90cstub.a           libhdf5_tools.a
libhdf5.so               libhdf5_fortran.so           libhdf5_hl_f90cstub.so          libhdf5_tools.so
libhdf5.so.310           libhdf5_fortran.so.310       libhdf5_hl_f90cstub.so.310      libhdf5_tools.so.310
libhdf5.so.310.5.0       libhdf5_fortran.so.310.3.1   libhdf5_hl_f90cstub.so.310.0.5  libhdf5_tools.so.310.0.5
libhdf5_f90cstub.a       libhdf5_hl.a                 libhdf5_hl_fortran.a            libhdf5hl_fortran.so
libhdf5_f90cstub.so      libhdf5_hl.so                libhdf5_hl_fortran.so           pkgconfig
libhdf5_f90cstub.so.310  libhdf5_hl.so.310            libhdf5_hl_fortran.so.310
```

```

**Comment by sumseq** [comment]
Hi,

I am not sure as the there are files in there that match the flags you are
using and other that are not.
Remember that a flag "-l<name>" typically refers to a file called
"-lib<name>.so".
Also it looks like the naming is different for the hl variety (more
underscores)

You may want to try:

-L/usr/local/hdf5/lib/ -lhdf5_fortran -lhdf5_hl_fortran -lhdf5 -lhdf5_hl

 - Ron

**Comment by sumseq** [comment]
Hi again,

Just saw that yout LD path has :  /usr/local/HDF_Group/HDF5/1.14.5/lib
and not:  /usr/local/hdf5/lib

It would be good to make sure the LD_LIBRARY_PATH and the -L directories
match before modifying the flag names.

 - Ron

**Comment by khayamgondal** [comment]
Thanks @sumseq for the help. I was able to build using` build_gpu_nvidia.sh` script and run open_field/ from run_examples/. 
To built with unified memory support, I copied `Makefile, pot3d_cpp.f90, luso_cusparse.c, psi_io.f90` from src/ to src/stdpar and built with the following changes in Makefile

```
FFLAGS = -O3 -march=native -mp=gpu -gpu=mem:unified -Minfo=accel $(ADDFLAGS) -I/usr/local/hdf5/include/
CCFLAGS = -O3 -march=native -mp=gpu -gpu=mem:unified -Minfo=accel $(ADDFLAGS)
```

However, openfield/ performs very slow with unified mem (total time 144s) compared to default flags in build_gpu_nvidia.sh (26s total time). With default one GPU usage was around 97% and with unified its only 3%. 

I am running it using ` mpiexec -np 1 --allow-run-as-root  --npersocket 1 ./pot3d_stdpar`

I also ran potential_field_current_sheet/ but performance is same. Any idea what could be problem here? Maybe I am missing some flags?

**Comment by sumseq** [comment]
Hi,

Those examples use the "ifprec=2" in their pot3d.dat which uses the ILU0
preconditioner.
That preconditioner only works on the GPU well when compiling with cuSparse
which I assume you have done?
(Check the build script/makefile and make sure it is linking cuSparse)

If it is being compiler with cusparse, it could be that the unified memory
is not properly recognizing the memory spaces in the calls to cuSparse,
while the manual memory mode explicitly uses the "device_ptr" clause.

A good test would be to change the pot3d.dat files for the two tests to use
"ifprec=1" and run with and without unified memory.

If those are similar, than I may want to look into the issue with the
cuSparse calls.

 - Ron

**Comment by khayamgondal** [comment]
Thanks @sumseq, performance delta is worse with ifprec=1, default openACC version takes (29s, GPU usage 89%), and the unified memory version takes (896s, GPU 1%)

I see the following warning for both openacc & unfied variants. HW is GH200, with H100 GPU. Based on Nvidia documentation, memory pinning is not required on GH200.
```

WARNING: Open MPI tried to bind a process but failed.  This is a
warning only; your job will continue, though performance may
be degraded.

  Local host:        e7259b49acde
  Application name:  ./pot3d_unified
  Error message:     failed to bind memory
  Location:          ../../../../../orte/mca/rtc/hwloc/rtc_hwloc.c:447

--------------------------------------------------------------------------
```
IMO, we can ignore the failed to bind memory error - this might be due to running it in a docker container, also GH200 is single socket, cache coherent. 

I am running it by using  `mpiexec -np 1 --allow-run-as-root  --npersocket 1 ./pot3d_unified `

**Comment by sumseq** [comment]
Hi,

I tested each code on an RTX 3090 Ti GPU and I get the following for the "open_field" example with the pot3d.dat modified to use ifprec=1:

Original/main code:
```
-O3 -march=native -stdpar=gpu -acc=gpu -mp=gpu -gpu=ccnative,mem:separate
```
```
mpiexec -np 1 ./pot3d 1>pot3d.log 2>pot3d.err
```

```
 Average time used per proc  =    24.831545
 Average comm. time per proc =     0.148655
```

Standard parallelism (stdpar):
```
-O3 -march=native -stdpar=gpu -gpu=ccnative,mem:unified
```
```
mpiexec -np 1 ./pot3d_unified 1>pot3d.log 2>pot3d.err
```

```
 Average time used per proc  =    25.036695
 Average comm. time per proc =     0.262065
```

Make sure that `ifprec=1` is only set once in the `pot3d.dat` files, and your compile flags match those above and it "should" work.

Note I am using the nvidia-open driver which is required for the `mem:unified` mode.

```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.01              Driver Version: 565.57.01      CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
```


 -- Ron

**Comment by khayamgondal** [comment]
Thanks Ron,` -stdpar=gpu` flag in CCFLAGS shows error ` nvc-Error-Unknown switch: -stdpar=gpu`
I changed the FFLAGS  to match yours
` FFLAGS = -O3 -march=native -stdpar=gpu -gpu=ccnative,mem:unified $(ADDFLAGS) -I/usr/local/hdf5/include/`
 and keeping 
`CCFLAGS = -O3 -march=native  -gpu=ccnative,mem:unified $(ADDFLAGS)` 
but I am seeing similar performance as my last comment.  I have ` ifprec=1 ` in pot3d.dat file.

_**Are you using `mpif90` compiler or a different one?**_ 

My Makefile looks like 

```
FC=mpif90

POT3D_CUSPARSE=1

ifeq ($(POT3D_CUSPARSE),1)
  IF_DEF = -DCUSPARSE
  CC = nvc
  ADDFLAGS = -cudalib=cusparse -lnvJitLink
  CCFLAGS = -O3 -march=native  -gpu=ccnative,mem:unified $(ADDFLAGS)
else
  IF_DEF = 
  ADDFLAGS = 
endif

FFLAGS = -O3 -march=native -stdpar=gpu -gpu=ccnative,mem:unified $(ADDFLAGS) -I/usr/local/hdf5/include/

OBJS0 = psi_io.o

ifeq ($(POT3D_CUSPARSE),1)
  OBJS = $(OBJS0) lusol_cusparse.o pot3d_cpp.o
else
  OBJS = $(OBJS0) pot3d_cpp.o
endif

LDFLAGS = -L/usr/local/hdf5/lib/ -lhdf5_fortran -lhdf5_hl_fortran -lhdf5 -lhdf5_hl 

all: $(OBJS)
	$(FC) $(FFLAGS) $(OBJS) $(LDFLAGS) -o pot3d
	rm -f *.mod *.o 2>/dev/null

clean:
	rm -f *.mod *.modmic *.o pot3d_cpp.f 2>/dev/null
	rm pot3d 2>/dev/null

pot3d_cpp.f90: pot3d.F90
	$(FC) -E -cpp $(IF_DEF) > pot3d_cpp.f90 $<

psi_io.o: psi_io.f90
	$(FC) -c $(FFLAGS) $<

lusol_cusparse.o: lusol_cusparse.c 
	$(CC) -c $(CCFLAGS) $<

pot3d_cpp.o: pot3d_cpp.f90
	$(FC) -c $(FFLAGS) $<
```

POT3D.dat file as following
```
 &topology
!
! Grid size (r,theta,phi).
!
  nr=201
  nt=181
  np=451
 /
 &inputvars
!
! Run type.
!
  option='open'
!
! Input options.
!
  br0file='br_input.h5'      
  phishift=0.0               
  do_not_balance_flux=.true.
!
! Domain (radial).
!
  r0=1.0
  r1=20.0
!
! Grid specification
!
  rfrac=0.0,1.0
  drratio=40.0
  nfrmesh=5
!
  tfrac=0.00,0.50,1.00
  dtratio=0.5,2.0
  nftmesh=5
!
  pfrac=0.00
  dpratio=1.0
  nfpmesh=5
!
! Output options. 
!
  brfile='br_open.h5'       
  btfile='bt_open.h5'       
  bpfile='bp_open.h5'       
  br_photo_file=''          
  br_photo_original_file='' 
  phifile=''                
  hdf32=.false.             
!
! Solver options.
!
  ifprec=1              
  epscg=1.e-9           
  ncghist=100 
  ncgmax=10000000       
!
! Debugging flag.
!
  idebug=0
 /
```

I am using nvidia-driver-550 -open
![image](https://github.com/user-attachments/assets/1396a468-17b0-47fc-b591-a6b510661ecc)
![image](https://github.com/user-attachments/assets/99ede7b6-abd7-4fad-84ee-cc27c7ff5924)

**Comment by khayamgondal** [comment]
I am able to build and run it and get similar performance as OpenACC

Thanks for the help, Ron
