### ISSUE TITLE
hdf5 version tested and parallel hdf5?

### ISSUE THREAD

**Issue by kurtsansom** [predsci/POT3D#2]
What version of hdf5 is POT3D used with?

Is using the serial hdf5 libraries required?

**Comment by sumseq** [comment]
Hello,

It has been tested with multiple versions, including 1.8.21.
It has also been tested to work with the serial version that is in the
Ubuntu 20.04 APT package.

I have not tried to use the parallel hdf5 library, so I do not know if it
is compatible with that.

Thanks for the interest!

 - Ron

**Comment by kurtsansom** [comment]
I just tried it with `hdf5@1.10.7` with mpi enabled and the validation tests passed. (local build of hdf5).
Will let you know if issues come up.
Thank you.
