### ISSUE TITLE
Output dimensions not the same?

### ISSUE THREAD

**Issue by kurtsansom** [predsci/POT3D#3]
Reading the output hdf5 files from `potential_field_source_surface` example
the dimensions of the do not appear to match is there a reason for this?
it appears to be "off by 1" for each dimension.
```py
import h5py
import os

dir_path = "../POT3D/examples/potential_field_source_surface"

sol_br = h5py.File(os.path.join(dir_path, 'br_pfss.h5'), 'r')
sol_bt = h5py.File(os.path.join(dir_path, 'bt_pfss.h5'), 'r')
sol_bp = h5py.File(os.path.join(dir_path, 'bp_pfss.h5'), 'r')

# transpose gives dim1, dim2, dim3
print(sol_br["Data"][:].T.shape)
print(sol_bt["Data"][:].T.shape)
print(sol_bp["Data"][:].T.shape)
```
gives

```sh
(132, 181, 451)
(133, 180, 451)
(133, 181, 450)
```

**Comment by rl1234567890** [comment]
It is a feature. The magnetic field is derived using finite difference derivatives from the scalar potential. Since Br is obtained through derivation along r, it has one point less in the radial direction. Similarly for Bt and Bp, for which we apply respectively a derivation along the second (theta) and third (phi) dimension.

**Comment by sumseq** [comment]
Hello,

Yes, this is correct as the field is staggered differently in each
component.

So for Br, the radial grid lands on the boundary, but in the theta and phi
directions, the field is staggered.
For example, the last theta point in Br is a ghost cell "past the pole" but
set such that the average of it and the inner point is the polar value.

The best way to see this is to print out the r, t, and p 1D grid "scale"
arrays for each component and the staggering will be seen
(h5file['Data'].dims[#][0], #->{0,1,2})  an example python function to do
this is below.

A visual for this can be seen for our other code MAS, here:
http://www.predsci.com/images/MAS_mesh.pdf

The POT3D grid staggering of "B" is the same as the MAS grid staggering of
"V".

We plan to add more documentation and some simple python scripts for
reading/interpolating the data in the future.

Hope that helps!

 - Ron

-------------------------------------------

def rdh5(h5_filename):
    x = np.array([])
    y = np.array([])
    z = np.array([])
    f = np.array([])

    h5file = h5.File(h5_filename, 'r')
    f = h5file['Data']
    dims = f.shape
    ndims = np.ndim(f)

    #Get the scales if they exist:
    for i in range(0,ndims):
        if i == 0:
            if (len(h5file['Data'].dims[0].keys())!=0):
                x = h5file['Data'].dims[0][0]
        elif i == 1:
            if (len(h5file['Data'].dims[1].keys())!=0):
                y = h5file['Data'].dims[1][0]
        elif i == 2:
            if (len(h5file['Data'].dims[2].keys())!=0):
                z = h5file['Data'].dims[2][0]

    x = np.array(x)
    y = np.array(y)
    z = np.array(z)
    f = np.array(f)

    h5file.close()

    return (x,y,z,f)

**Comment by kurtsansom** [comment]
Thank you for the clarification, closing due to "not an error"

I am trying to read the data into format that I can apply stream tracing to. (attempting with VTK)

With the staggered grid as this I suppose I need to map the solution points for the magnetic field to cell centers or a common location to get it in a `vector` format for the stream tracing.  i.e. interpolating as you propose.

gracias.

**Comment by sumseq** [comment]
Hi,

If you simply take the average between cells along the 2 staggered
directions for each component, you should end up with each component on the
same grid.
Note, this will add a bit of interpolative smoothing to those two
directions for each component, but it should not be too much of an issue.

 - Ron

**Comment by kurtsansom** [comment]
@sumseq 
Thank you for the input. Is there additional value in doing more sophisticated interpolation?

here is what I came up with for getting the grid dimensions and the average of each field.

```py
import h5py
import os

def map_staggered(dir_path, file_name_list):
  dims = {}
  for B, value in file_name_list.items():
    sol_b = h5py.File(os.path.join(dir_path, value), 'r')
    data = sol_b["Data"][:]
    K, M, N = data.shape
    if B == "Br":
      dims["r"] = sol_b["dim1"][:]
      avg_1 = (data[0:K-1,:,:] + data[1:K,:,:])/2.0
      avg_2 =  (avg_1[:,0:M-1,:] + avg_1[:,1:M,:])/2.0
      dims["Br"] = avg_2
    elif B == "Bt":
      dims["t"] = sol_b["dim2"][:]
      avg_1 = (data[0:K-1,:,:] + data[1:K,:,:])/2.0
      avg_2 =  (avg_1[:,:,0:N-1] + avg_1[:,:,1:N])/2.0
      dims["Bt"] = avg_2
    elif B == "Bp":
      dims["p"] = sol_b["dim3"][:]
      avg_1 = (data[:,0:M-1,:] + data[:,1:M,:])/2.0
      avg_2 =  (avg_1[:,:,0:N-1] + avg_1[:,:,1:N])/2.0
      dims["Bp"] = avg_2
    else:
        print("error somehow")

  return dims
```

**Comment by rl1234567890** [comment]
What makes sense is to use an interpolation method that preserves div B = 0.
