### ISSUE TITLE
POT3D compilation problem

### ISSUE THREAD

**Issue by rahahahat** [predsci/POT3D#5]
Hello I'm trying to compile POT3D and I'm getting these errors. Any help regarding this would be highly appreciated.

### Output
```

 4606 |       call load_lusol_cusparse (C_LOC(a_csr(1)),
      |                                      1
Error: Argument X at (1) to C_LOC shall have either the POINTER or the TARGET attribute
pot3d.F:5155:34:

 5155 |         call lusol_cusparse(C_LOC(x(1)))
      |                                  1
Error: Argument X at (1) to C_LOC shall have either the POINTER or the TARGET attribute
pot3d.F:5601:39:

 5601 |       call MPI_Allreduce (MPI_IN_PLACE,x,1,ntype_real,
      |                                       1
......
 6065 |       call MPI_Allreduce(MPI_IN_PLACE,w,3,ntype_real,
      |                                      2 
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
pot3d.F:3726:22:

 1015 |       call MPI_Bcast (ierr0,1,MPI_INTEGER,0,MPI_COMM_WORLD,ierr)
      |                      2
......
 3726 |       call MPI_Bcast (br0_g,nt_g*np_g,ntype_real,0,comm_all,ierr)
      |                      1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
pot3d.F:2168:26:

 2168 |       call MPI_Allgather (sbuf,lbuf,MPI_INTEGER,
      |                          1
......
 6337 |       call MPI_Allgather (sbuf,lbuf,ntype_real,
      |                          2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(8)).

```
### Details
- MPI module `cray-mpich/8.1.11`
- `ftn --version ` outputs `GNU Fortran (GCC) 11.2.0 20210728 (Cray Inc.)`
- `nvcc --version` outputs `cuda_11.5`

**Comment by rahahahat** [comment]
**Update**:
I was able to suppress the mismatch errors into warnings by using the `-fallow-argument-mismatch` compiler flag. 
However, the `C_LOC` errors still persist.
```
 4606 |       call load_lusol_cusparse (C_LOC(a_csr(1)),
      |                                      1
Error: Argument X at (1) to C_LOC shall have either the POINTER or the TARGET attribute
pot3d.F:5155:34:

 5155 |         call lusol_cusparse(C_LOC(x(1)))
      |                                  1
Error: Argument X at (1) to C_LOC shall have either the POINTER or the TARGET attribute
pot3d.F:5601:39:
```

**Comment by sumseq** [comment]
Hello,

Thanks for pointing this out.
It seems gfortran is more picky about the spec than nvfortran is.
I am updating the code and build scripts to fix this and will push it up
when done.

 - Ron

**Comment by sumseq** [comment]
Hi again,

Actually  - it looks like you are trying to compile POT3D with gfortran and
using the cuSparse library.
This is NOT currently supported since POT3D now uses "do concurrent" for
GPU acceleration, which is not yet supported in gfortran.
You may want to set POT3D_CUSPARSE=0 in your build script.

If you replace all "do concurrent" loops in POT3D with regular nested "do"
loops and add the appropriate OpenACC pragmas,
you could then install the GPU version with gfortran, and link it to the
CUDA library cuSparse (we have indeed tested this with a previous version).

 - Ron

**Comment by sumseq** [comment]
OK new version is up!

 - Ron

**Comment by rahahahat** [comment]
This is great. Thank you so much.
 I'm not sure if my fix is correct or not but I managed to **FIX** the `C_LOC` errors and compile pot3d by making the following changes in **pot3d.F** :
 ```
#-------------------------------------------------------
subroutine prev_inv(x)
(line 5148)real(r_typ),target,dimension(N) :: x

Note: Doing this gave me an error which prompted me to define an explicit interface for prec_inv (See below)
#--------------------------------------------------------------------

 (line 4195) subroutine cgsolve (x,r,N,ierr)
 !implicit none (commented it out)
       interface
          subroutine prec_inv (x)
              use number_types
              use number_types_pc
              use cgcom
              use solve_params
              use matrix_storage_pot3d_solve
              use, intrinsic :: iso_c_binding
              use cusparse_interface
              use timing
              implicit none        
              real(r_typ),target,dimension(N) :: x
              real(r_typ_pc), dimension(N) :: x_32
              integer :: i
          end subroutine prec_inv
      end interface

#------------------------------------------------------------------------------

module matrix_storage_pot3d_solve
(line 645) real(r_typ_pc), dimension(:), allocatable, target :: a_csr
(line 649) integer, dimension(:), allocatable, target :: a_csr_ia
(line 650) integer, dimension(:), allocatable, target :: a_csr_ja

#--------------------------------------------------------------------------------


 ```
One thing I would like to point out though is that although I'm able to compile pot3d successfully now, it doesn't work and gives me the error `[PE_0]:_pmi_applist_setup:App list is not supported for this job!`
Which I thought could to be a problem with `hdf5` even though I'm using the serial based on what I saw [here](https://docs.nersc.gov/development/libraries/hdf5/#known-issues-on-perlmutter), although I now think this could be related to gfortran `do concurrent`.

Thanks a lot for your help. I appreciate it.

**Comment by sumseq** [comment]
Hi,

The newest update now uses "target" on all applicable arrays and seems to
work without needing that interface.

Note that it is using:
real(r_typ), dimension(N), target :: p,ap
where "p" and "ap" are the arrays passed to "prec_inv()".
Inside prec_inv(), I do not use the target attribute, as it is already on
the arrays being passed in.
Does GCC complain even with that?  Does it still need "target" on "x"?

As I mentioned in my last messages, you cannot currently use POT3D on GPUs
with GCC because POT3D uses "do concurrent" for GPU-offload, and GCC
doesn't yet support that.

For GCC on the CPU, you should be able to modify and use one of the GCC
build scripts in the "build_examples" folder.

 - Ron

**Comment by sumseq** [comment]
Hi again,

I had the same problem as you did.

Make sure you run "clean.sh" before trying to build the updated code.
For some reason, even with CUSPARSE off, my build was old and had the C_LOC
calls in it.

 - Ron

**Comment by rahahahat** [comment]
> Hi, The newest update now uses "target" on all applicable arrays and seems to work without needing that interface. Note that it is using: real(r_typ), dimension(N), target :: p,ap where "p" and "ap" are the arrays passed to "prec_inv()". Inside prec_inv(), I do not use the target attribute, as it is already on the arrays being passed in. Does GCC complain even with that? Does it still need "target" on "x"? As I mentioned in my last messages, you cannot currently use POT3D on GPUs with GCC because POT3D uses "do concurrent" for GPU-offload, and GCC doesn't yet support that. For GCC on the CPU, you should be able to modify and use one of the GCC build scripts in the "build_examples" folder. - Ron

I haven't tried the newest changes yet. Since I need the `cuSPARSE` library as a part of my research project, I'm currently setting up an alternate compiler, which requires me to build `hdf5` with the same. I'll update this issue once I make some more progress.

I'm grateful for all your help. Thanks a lot! 
Rahat

**Comment by sumseq** [comment]
OK great sounds good.

I recently gave a talk at GTC on cuSparse in POT3D.

You can check out the slides here:
https://www.sumseq.com/files/2022_NVIDIA_Talk_RCaplan.pdf
Maybe it can be helpful.

 - Ron

**Comment by rahahahat** [comment]
> OK great sounds good. I recently gave a talk at GTC on cuSparse in POT3D. You can check out the slides here: https://www.sumseq.com/files/2022_NVIDIA_Talk_RCaplan.pdf Maybe it can be helpful. - Ron


Thanks for the slides. These are great.
I attended your GTC talk. It was really helpful and interesting.

**Comment by rahahahat** [comment]
@sumseq Hello, I was able to compile and run POT3D using the nvfortran (with included mpi library).
Thanks for your help. 
Closing this issue now.
