### ISSUE TITLE
What is CORHEL or PSITOOLS 

### ISSUE THREAD

**Issue by Luo-Yihang** [predsci/POT3D#9]
Hi! I was tring to plot the POT3D input data.

May I know what is CORHEL or PSITOOLS that is required by the plotting script `scripts/psipals.py`. I tried to search those online, but nearly nothing is related. But it seems we must install one of them before running the plotting scripts.

Thank you!

**Comment by sumseq** [comment]
Hi,

Those two packages are not open source yet.

I will add the nessesary files to the scripts to allow the use of plot2d some time in the next two weeks.

Thanks for your question!

 - Ron

**Comment by sumseq** [comment]
Hello,

I have made the updates needed to use the psi_plot2d.

Please let me know if there are any problems.

 - Ron
